POST http://localhost:3001/campaigns HTTP/1.1
content-type: application/json

{
  "nome": "Campanha 32",
  "dataInicio": "2024-08-09T00:12:18.000Z",
  "dataFim": "2024-09-01T00:12:18.000Z",
  "categoryId": 4
}

###
GET http://localhost:3001/campaigns HTTP/1.1

###
GET http://localhost:3001/campaigns/1 HTTP/1.1

###
PUT http://localhost:3001/campaigns/27 HTTP/1.1
content-type: application/json

{
  "nome": "Campanha 2",
  "dataInicio": "2024-07-16T00:00:00.000Z",
  "dataFim": "2024-08-08T23:59:59.999Z",
  "categoryId": 2,
  "status": "ativa"
}

###
DELETE http://localhost:3001/campaigns/28 HTTP/1.1

###
POST http://localhost:3001/categories HTTP/1.1
content-type: application/json

{
  "name": "Categoria 3"
}

###
GET http://localhost:3001/categories HTTP/1.1

###
GET http://localhost:3001/categories/1 HTTP/1.1